export const shipConfig = {
  destroyer: {
    label: "Destroyer",
    health: 64,
    speed: 1.3,
    damage: 2,
    fireRate: 500,
    skillCooldown: 5000,
    skillType: "torpedo",
    color: "#6ee7b7",
    turretSpec: { count: 2, maxRounds: 2, cooldownMs: 1000 },
    width: 150,
    height: 150,
    hitboxLong: 120,
    hitboxShort: 28,
  },
  cruiser: {
    label: "Cruiser",
    health: 128,
    speed: 1.25,
    damage: 2,
    fireRate: 600,
    skillCooldown: 10000,
    skillType: "overdrive",
    color: "#93c5fd",
    turretSpec: { count: 3, maxRounds: 2, cooldownMs: 3000 },
    width: 175,
    height: 175,
    hitboxLong: 135,
    hitboxShort: 44,
  },
  battleship: {
    label: "Battleship",
    health: 512,
    speed: 1,
    damage: 4,
    fireRate: 1200,
    skillCooldown: 15000,
    skillType: "barrage",
    color: "#fca5a5",
    turretSpec: { count: 3, maxRounds: 3, cooldownMs: 6500 },
    width: 200,
    height: 200,
    hitboxLong: 165,
    hitboxShort: 60,
  },
  carrier: {
    label: "Aircraft Carrier",
    health: 254,
    speed: 0.7,
    damage: 1,
    fireRate: 100,
    skillCooldown: 10000,
    skillType: "planes",
    color: "#fde68a",
    turretSpec: null,
    planeStock: { torpedo: 4, dive: 4 },
    width: 225,
    height: 225,
    hitboxLong: 195,
    hitboxShort: 45,
  },
};
