export const state = {
  gameState: "start",
  mode: "pvp",
  playerClass: null,
  player2Class: null,
  enemyClass: null,
  pendingClass: null,
  paused: false,
  coopWave: 0,
  coopTotalWaves: 5,
  campaignMission: 0,
  campaignMode: false,
  waveTransitionTimer: 0,
  stats: {
    p1ShotsFired: 0,
    p2ShotsFired: 0,
    p1DamageDealt: 0,
    p2DamageDealt: 0,
    matchTimeMs: 0,
  },
};
